### ISSUE TITLE
touchEnd事件中未对timeStamp做判空处理

### ISSUE THREAD

**Issue by whutyzy** [ScoutYin/ly-tab#12]
移动端使用时，在特定的情形中，click会触发touch,touchEnd事件，此时`timeStamp = this.endMoveTime - this.startMoveTime`的值为0，在`this.speed = (this.lastX - this.startX) / timeStamp`会生成NAN,最后影响到translateX为NAN，导致页面无法滑动

**Comment by ScoutYin** [comment]
谢谢，已经修复。
