### ISSUE TITLE
 v-model="selectedId" 在页面刚刚执行的时候，动态给赋值没有效果。

### ISSUE THREAD

**Issue by Shangri-GitHub** [ScoutYin/ly-tab#14]
在页面刚刚执行的时候，动态给赋值没有效果
 mounted: function () {
      this.selectedId = 2;
 }

**Comment by Shangri-GitHub** [comment]
已解决，用这个可以
beforeMount: function () {
      this.selectedId = 2;
    },

**Comment by haocaiMP** [comment]
可以根据 selectedId 值的改变 控制导航定位吗？

**Comment by ScoutYin** [comment]
是在什么钩子函数里赋值的呢，改变selectId是可以控制导航位置的




| |
尹斌
邮箱：yinbin_web@163.com
|

签名由 网易邮箱大师 定制

在2018年10月10日 09:25，haocaiMP 写道：

可以根据 selectedId 值的改变 控制导航定位吗？
