### ISSUE TITLE
请问是否支持异步加载数据，若支持，异步加载数据时，ly-tab-active-bar 的宽度为 0

### ISSUE THREAD

**Issue by huxianguan** [ScoutYin/ly-tab#20]
利用ajax 异步加载数据，selectedId 默认为零，文字下面ly-tab-active-bar宽度为0
如图：
![image](https://user-images.githubusercontent.com/18564236/46590428-c36fb680-cae5-11e8-9c47-4814c749bcea.png)
初始化的时候

**Comment by ScoutYin** [comment]
如果需要异步获取tab数据的话，建议先使用v-if控制组件的初始化，等待数据获取成功再初始化组件
