### ISSUE TITLE
create中初始化完tabs，变更selectId,ly-tab-active-bar没宽度

### ISSUE THREAD

**Issue by shenzudan** [ScoutYin/ly-tab#27]
![image](https://user-images.githubusercontent.com/17032816/55243369-10a13980-527a-11e9-8862-9613264c1beb.png)

![image](https://user-images.githubusercontent.com/17032816/55243402-2282dc80-527a-11e9-9d3b-0b788bb61cee.png)

**Comment by Liuweina** [comment]
请问解决了吗

**Comment by ScoutYin** [comment]
该问题已在3.x版本中解决了，3.x版本与2.x版本存在api及使用上的差异，但升级成本不高，建议升级为最新的3.x版本
