### ISSUE TITLE
下载了项目运行不出来

### ISSUE THREAD

**Issue by LoisLuo** [ScoutYin/ly-tab#3]

**Comment by ScoutYin** [comment]
是安装node-sass出错了，可以通过全局配置node-sass下载仓库为淘宝镜像解决，先yarn remove node-sass 或者npm uninstall node-sass卸载安装出错的node-sass，然后npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/设置下载源，再执行node-sass安装，就没问题了
