### ISSUE TITLE
请问options里有哪些参数是允许我们进行设置的

### ISSUE THREAD

**Issue by kido050313** [ScoutYin/ly-tab#31]
对于
```
 options: {
        activeColor: '#1d98bd'
        // 可在这里指定labelKey为你数据里文字对应的字段名
      },
```
中的注释那段话有点不太懂，labelkey是指什么，怎么使用呢？

**Comment by ScoutYin** [comment]
请参照[2.x版本文档说明](https://github.com/ScoutYin/ly-tab/tree/2.x#%E5%8F%AF%E9%80%89%E7%9A%84%E9%85%8D%E7%BD%AE%E9%A1%B9)。

建议升级[3.x版本](https://github.com/ScoutYin/ly-tab/tree/master#ly-tab-3x%E7%89%88%E6%9C%AC%E9%9D%9Evue3)
