### ISSUE TITLE
当数据为动态可变时，宽度未变，左右拉动出现问题，应该重新计算listWidth的宽度才对

### ISSUE THREAD

**Issue by zb19880103** [ScoutYin/ly-tab#33]
当数据是动态的，比如我点击某个按钮，数据增加，问题是数据确实加入进去了，但没有重新计算listWidth的宽度，导致最后拉不到底，比如之前10个数据，宽度是1000，可以拉到最右侧，变成15条数据后，宽度应该是1500才能拉到最右侧，但宽度没有重新计算还是1000没变，所以最后的几条拉不出来看不到了，不知道我描述明白没，有点啰嗦，呵呵，我现在是加了个v-if后， watch监听数据变化后，改变v-if的值，销毁再创建，这样是可以解决问题，但挺麻烦的

**Comment by ScoutYin** [comment]
该问题已在3.x版本中修复，请升级最新版本，3.x版本API存在变更，请参照文档说明使用，谢谢。

**Comment by zb19880103** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
