### ISSUE TITLE
关于该控件的一点点小的建议，

### ISSUE THREAD

**Issue by luochenLing** [ScoutYin/ly-tab#34]
作者你好，关于这个插件，他的销毁阶段是否是不可以调用到 this.$refs里面的属性了已经，是否应该在beforedestory里面进行完成移除事件的操作呢，根据您的源码我编写了一个竖版的分类导航发现的这个问题

**Comment by ScoutYin** [comment]
感谢指出，确实应该在组件 beforeDestroy 生命周期中移除事件，已修复。
