### ISSUE TITLE
Unexpected token operator «=», expected punc «,» [./~/ly-tab/index.js:3,0]（已解决！）

### ISSUE THREAD

**Issue by AndyJaa** [ScoutYin/ly-tab#38]

**Comment by AndyJaa** [comment]
已解决，在webpack.conf.js文件中配置如下
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/ly-tab/index')]
      }

**Comment by ScoutYin** [comment]
由于历史原因，2.x版本的npm包中的组件代码是未编译过的源代码，开发时需要配合webpack使用loader处理，你可以升级到3.x的最新版本，不再需要webpack等打包工具进行处理了，3.x版本与2.x版本存在API变更，请参照文档进行升级，谢谢。
