### ISSUE TITLE
如何获取按钮的值，不是获取index

### ISSUE THREAD

**Issue by Hxiaotong** [ScoutYin/ly-tab#6]

**Comment by ScoutYin** [comment]
不知道你的需求是什么，为何需要获取按钮的值，这个组件是个tab组件，只要知道点击的是哪个（或者说第几个），然后做相应操作（一般是切换路由或者视图）不就好了吗

**Comment by ScoutYin** [comment]
https://github.com/ScoutYin/ly-tab/blob/master/CHANGELOG_CN.md
